version: '3.3'
services:
  iiif_edge_lambdas:
    build:
      context: ./cloudfront/iiif.wellcomecollection.org/edge-lambda
  wellcome_library_edge_lambdas:
    build:
      context: ./cloudfront/wellcomelibrary.org/edge-lambda